# Generated by Django 5.2.8 on 2025-11-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100)),
                ('Weather', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Map', models.URLField(max_length=300)),
                ('Description', models.CharField(max_length=5000)),
                ('Image', models.ImageField(upload_to='destinations/')),
            ],
        ),
    ]
